version: 2

models:
  - name: stg_localbike_database__brand
    description: "This model contains information about brand"
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand"
        tests:
            - unique
            - not_null





  - name: stg_localbike_database__category
    description: "This model contains information about category"
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each category"
        tests:
            - unique
            - not_null

  - name: stg_localbike_database__store
    description: "This model contains information about store"
    columns:
      - name: store_id
        description: "Primary key, unique identifier for each category"
        tests:
            - unique
            - not_null





  - name: stg_localbike_database__order
    description: "This model contains information about orders placed by users, including the status of each order."
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
            - unique
            - not_null

      - name: customer_id
        description: "Foreign key linking the order to the user who placed it."
        tests:
          - relationships:
              name: customer_id_id_foreign_key_in_stg_localbike_database__order
              to: ref('stg_localbike_database__customer')
              field: customer_id






  - name: stg_localbike_database__order_item
    description: "This model contains information about each item included in an order, including its price, quantity, and shipping cost."
    columns:
      - name: item_id
        description: "Primary key, unique identifier for each order item."
        tests:
            - unique
            - not_null
      - name: order_id
        description: "Foreign key linking the order item to the corresponding order."
        tests:
          - relationships:
              name: order_id_id_foreign_key_in_stg_localbike_database__order_item
              to: ref('stg_localbike_database__order')
              field: order_id
              
      - name: total_order_item_amount
        description: "The total amount for this order item, calculated as (list_price * quantity) * (1-discount)"






  - name: stg_localbike_database__product
    description: "This model contains details of products available for sale, primarily focusing on information about the product's volume and size."
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null
      - name: brand_id
        description: "Foreign key linking the order to the user who placed it."
        tests:
          - relationships:
              name: brand_id_id_foreign_key_in_stg_localbike_database__product
              to: ref('stg_localbike_database__brand')
              field: brand_id
      - name: category_id
        description: "Foreign key linking the order to the user who placed it."
        tests:
          - relationships:
              name: category_id_id_foreign_key_in_stg_localbike_database__product
              to: ref('stg_localbike_database__category')
              field: category_id




  - name: stg_localbike_database__stock
    description: "This model contains details of stock."
    columns:
      - name: store_id
        description: "Foreign key linking the order to the user who placed it."
        tests:
          - relationships:
              name: store_id_id_foreign_key_in_stg_localbike_database__product
              to: ref('stg_localbike_database__store')
              field: store_id
      - name: product_id
        description: "Foreign key linking the order to the user who placed it."
        tests:
          - relationships:
              name: product_id_id_foreign_key_in_stg_localbike_database__product
              to: ref('stg_localbike_database__product')
              field: product_id



  - name: stg_localbike_database__staff
    description: "This model contains information about the sellers who provide the products."
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each seller."
        tests:
            - unique
            - not_null
      - name: manager_id
        description: "Foreign key linking the order to the user who placed it."
        tests:
          - relationships:
              name: manager_id_id_foreign_key_in_stg_localbike_database__order
              to: ref('stg_localbike_database__staff')
              field: staff_id
      - name: store_id
        description: "Foreign key linking the order to the user who placed it."
        tests:
          - relationships:
              name: store_id_id_foreign_key_in_stg_localbike_database__order
              to: ref('stg_localbike_database__store')
              field: store_id




  - name: stg_localbike_database__customer
    description: "This model contains customer-related information, including where they live."
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer."
        tests:
            - unique
            - not_null
