version: 2

models:
  - name: stg_localbike_database__brand
    description: "This model contains information about brand"
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand"
        tests:
            - unique
            - not_null

  - name: stg_localbike_database__category
    description: "This model contains information about category"
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each category"
        tests:
            - unique
            - not_null

  - name: stg_localbike_database__order
    description: "This model contains information about orders placed by users, including the status of each order."
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
            - unique
            - not_null
      - name: order_status
        description: "The current status of the order."
        tests:
          - accepted_values:
              name: accepted_values_order_status
              values: ['created', 'shipped', 'approved', 'canceled', 'invoiced', 'delivered', 'processing', 'unavailable']
      - name: customer_id
        description: "Foreign key linking the order to the user who placed it."
        tests:
          - relationships:
              name: user_id_id_foreign_key_in_stg_sales_database__order
              to: ref('stg_sales_database__user')
              field: user_id

  - name: stg_localbike_database__order_item
    description: "This model contains information about each item included in an order, including its price, quantity, and shipping cost."
    columns:
      - name: item_id
        description: "Primary key, unique identifier for each order item."
        tests:
            - unique
            - not_null
      - name: order_id
        description: "Foreign key linking the order item to the corresponding order."
        tests:
          - relationships:
              name: order_id_id_foreign_key_in_stg_sales_database__order_item
              to: ref('stg_sales_database__order')
              field: order_id
              
      - name: total_order_item_amount
        description: "The total amount for this order item, calculated as (price * quantity) + shipping_cost."


  - name: stg_localbike_database__product
    description: "This model contains details of products available for sale, primarily focusing on information about the product's volume and size."
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null

  - name: stg_localbike_database__staff
    description: "This model contains information about the sellers who provide the products."
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each seller."
        tests:
            - unique
            - not_null
      - name: manager_id
        description: "Foreign key linking the order to the user who placed it."
        tests:
          - relationships:
              name: manager_id_id_foreign_key_in_stg_localbike_database__order
              to: ref('stg_localbike_database__staff')
              field: staff_id

  - name: stg_localbike_database__customer
    description: "This model contains customer-related information, including where they live."
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer."
        tests:
            - unique
            - not_null
