version: 2

sources:
  - name: localbike_database
    schema: localbike_database
    tables:
      - name: brands
      - name: categories
      - name: customers
      - name: order
      - name: order_item
      - name: products
      - name: staffs
      - name: stocks
      - name: stores